apiVersion: v2
name: prometheus-cluster-role
description: ClusterRole for Prometheus monitoring
type: application
version: 0.1.0
icon: https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/static/img/default-template-icon.png?raw=true